create table "public"."groups" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null default ''::text,
    "badge" text not null default ''::text,
    "user" uuid not null default auth.uid()
);


alter table "public"."groups" enable row level security;

CREATE UNIQUE INDEX groups_pkey ON public.groups USING btree (id);

alter table "public"."groups" add constraint "groups_pkey" PRIMARY KEY using index "groups_pkey";



